// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE8-6s2qv9c4AY9bPquzqz4recucqttpI',
    appId: '1:616777944660:web:7e7fe70ec4d758e79727c1',
    messagingSenderId: '616777944660',
    projectId: 'csclubquizmakerapp',
    authDomain: 'csclubquizmakerapp.firebaseapp.com',
    storageBucket: 'csclubquizmakerapp.appspot.com',
    measurementId: 'G-0FZV4YWJVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFRlXUxfBQ0FN48V5g19db8WEQaS75xvA',
    appId: '1:616777944660:android:93c8f023b390703a9727c1',
    messagingSenderId: '616777944660',
    projectId: 'csclubquizmakerapp',
    storageBucket: 'csclubquizmakerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvfNbLKOw2iF8OE9_PxWnCXicYT4eKtI',
    appId: '1:616777944660:ios:e002d3e1764ce3d89727c1',
    messagingSenderId: '616777944660',
    projectId: 'csclubquizmakerapp',
    storageBucket: 'csclubquizmakerapp.appspot.com',
    iosClientId: '616777944660-itrv3t4o18juotaf0mu3jo0bbrfdjepm.apps.googleusercontent.com',
    iosBundleId: 'com.example.csquizapp',
  );
}
